export const AUTH_START = "AUTH_START";
export const LOGGED_IN = "LOGGED_IN";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOG_OUT = "LOG_OUT";
export const RELOAD_START = "RELOAD_START";
export const RELOAD_USER = "RELOAD_USER";
export const RELOAD_USER_FAIL = "RELOAD_USER_FAIL";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const START_EDITING = "START_EDITING";
export const STOP_EDITING = "STOP_EDITING";
export const PROFILE_EDITING = "PROFILE_EDITING";
export const PROFILE_EDITING_FAIL = "PROFILE_EDITING_FAIL";
export const PROFILE_EDITED = "PROFILE_EDITED";
export const SET_MESSAGE = "SET_MESSAGE";
export const SHOW_EDIT_DIALOG = "SHOW_EDIT_DIALOG";
export const SHOW_DELETE_DIALOG = "SHOW_DELETE_DIALOG";
export const HIDE_EDIT_DIALOG = "HIDE_EDIT_DIALOG";
export const HIDE_DELETE_DIALOG = "HIDE_DELETE_DIALOG";
